### ISSUE TITLE
Feature Request - New Board Type

### ISSUE THREAD

**Issue by bleem313** [keiichiw/a-puzzle-a-day-solver#3]
A new type of puzzle a day has shown up that includes the day of the week. It uses all 9 of the previously defined pentominoes with the addition of the line tetromino. It continues the grid past day 31 to include the 7 weekdays but puts the last three on the bottom right instead of wrapping around.

<img src="https://user-images.githubusercontent.com/10550155/161815425-9f9bef50-1634-46c5-87a1-153232b6da53.jpg" height="300"><img src="https://user-images.githubusercontent.com/10550155/161815440-fabff9b7-17fa-45ff-a2a8-472fa1cae866.jpg" height="300">

I can't find information on the original creator, but it has appeared on a plethora of different websites.

The additional piece should be easy to add, but the new board type and third target would take a bit of code re-work I believe.

**Comment by keiichiw** [comment]
The internal structure of the board is just [a 2D vector](https://github.com/keiichiw/a-puzzle-a-day-solver/blob/0953a3306da526439fc5812a3a3b5767dd9a12fa/solver/src/board.rs#L32) and cells for "Month" and "Day" are handled similarly to the walls around the board. So I guess the code re-work isn't so big.

Since I don't own this variant of puzzles, it's unlikely that I'll implement this feature on my own anytime soon. But, any contribution is welcome!!

**Comment by anowell** [comment]
Fwiw, I discovered this repo after I had an alternate implementation - but I did add support for this board type in https://github.com/anowell/today-puzzle/pull/1

**Comment by keiichiw** [comment]
The puzzle was supported by #13. Thanks @mberneis !

@anowell, wow, it's interesting to see another solver for the same problem. Thank you for sharing your work.
